# Site settings
author: Jazmin
title: Jazmin's Blog
header-img: img/home-bg.png
email: jmatos1993@gmail.com
copyright_name: Jazmin
description: > # this means to ignore newlines until "baseurl:"
  Learn about Jazmin's Flatiron journey!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jazminmatos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
